<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>TIKSN.Habitica</RootNamespace>
    <AssemblyName>TIKSN.Habitica</AssemblyName>
    <LangVersion>latest</LangVersion>
    <PackageId>TIKSN-Habitica</PackageId>
    <Version>1.0.0</Version>
    <Authors>TIKSN</Authors>
    <Product>TIKSN</Product>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="10.0.10" />
    <PackageReference Include="RestSharp" Version="114.0.0" />
    <PackageReference Include="TIKSN-Framework" Version="5.7.3" />
  </ItemGroup>

</Project>
